import { Montserrat } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const montserratSans = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" scroll-behavior="smooth">
      <body className={`${inter.className} ${montserratSans.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
